server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  output:
    ansi:
      console-available: true
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cbuelvasc/banking-config-repo
          default-label: master
          clone-on-start: true
          timeout: 5
          force-pull: true